### ISSUE TITLE
Component Footer

### ISSUE THREAD

**Issue by ronan-haigo** [team-haigo/patterns-library#56]
<img width="1203" alt="Capture d’écran 2020-06-15 à 10 36 55" src="https://user-images.githubusercontent.com/66358717/84635884-238e4100-aef4-11ea-80a9-909b7bd4b352.png">

- [ ] Ce n'est pas le bon bleu AXA

**Comment by flexbox** [comment]
- [ ] Add a  screenshot of the footer with #4976ba
