### ISSUE TITLE
Adapt Component when the width is too large

### ISSUE THREAD

**Issue by ronan-haigo** [team-haigo/patterns-library#77]
In some case the component is too large : 
https://axa-design-system.netlify.app/components/hero
https://axa-design-system.netlify.app/components/footer

**PROBLEMS :**  it creates a horizontal scroll across the page because of the width of the component

**SOLUTION 1 :** 
scale automatically the component which can be include in the grid
ex : https://digitaldesign.vattenfall.com/css/footer

**SOLUTION 2 :** 
create a box which is inscribed in the grid in which the component is included and where the scroll acts only on this box (and no longer on the whole page)

**Comment by flexbox** [comment]
This one is duplicated with https://github.com/team-haigo/patterns-library/issues/26
