### ISSUE TITLE
Color page: Wrong content/ text on the "discover" link

### ISSUE THREAD

**Issue by johannabuguet** [team-haigo/patterns-library#83]
What it is now: 
![image](https://user-images.githubusercontent.com/68434693/88030850-09bbcb80-cb3c-11ea-8446-a0998f247385.png)

What it should be: 
<img width="739" alt="Capture d’écran 2020-07-21 à 10 23 35" src="https://user-images.githubusercontent.com/68434693/88031032-52738480-cb3c-11ea-9ed4-e11606a2d42d.png">

The last part of the page "colors" is about typography but it should be about colors

Expected Behavior:
- The text has to be changed (@flexbox Ronan have the design ready)
- the button should lead to this page : https://design.axa.com/web-guidelines/color

Current Behavior:
- wrong text
- wrong link

**Comment by Remy-haigo** [comment]
should be solved with changes in commit d79efe2bca9bd9aa0a637a0d6905493b3cf3e98d
