### ISSUE TITLE
Getting started page: The button "know more" leads to the wrong page

### ISSUE THREAD

**Issue by johannabuguet** [team-haigo/patterns-library#85]
![image](https://user-images.githubusercontent.com/68434693/88041463-b9983580-cb4a-11ea-8766-d7cf94ad014f.png)

Current behaviour: The button "know more" on the "getting started" page leads to the wrong page.

Expected Behavior: the button should open the "structure approach" page

**Comment by Remy-haigo** [comment]
should be fix with commit 561b1680a999c2d6d1b57f5473e17d043c3331ae
