### ISSUE TITLE
Getting started page: 404 Error on the AXA DS UI kit 

### ISSUE THREAD

**Issue by johannabuguet** [team-haigo/patterns-library#86]
![image](https://user-images.githubusercontent.com/68434693/88041546-db91b800-cb4a-11ea-9d70-b7c9a73ba8cb.png)

The button "download the AXA design system UI kit" on the "getting started" page, leads to a 404 error.

Expected Behavior: the button should lead the user to the brand hub: https://brandhub.axa.com/media/?mediaId=1EB5A285-444E-47F8-AEF1F5E7EE14106A

Current Behavior: the button leads to a 404 error

**Comment by Remy-haigo** [comment]
should be solved with changes in commit d79efe2bca9bd9aa0a637a0d6905493b3cf3e98d
